# Generated by Django 3.2.12 on 2022-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
